import { Metadata } from 'next';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

const FAQS = [
  {
    question: 'What is this website about?',
    answer:
      'This website is a travel blog that introduces various tourist destinations. We also have an AI Travel Planner that can help you create a travel plan.',
  },
  {
    question: 'How do I use the AI Travel Planner?',
    answer:
      'You can access the AI Travel Planner from the main menu. Simply input your destination, duration, and interests, and the AI will generate a customized travel plan for you.',
  },
  {
    question: 'Are the travel plans generated by the AI reliable?',
    answer:
      'The AI-generated travel plans are based on a vast amount of data and are designed to be helpful. However, we recommend using them as a reference and adjusting them to your specific needs.',
  },
  {
    question: 'Can I book flights or hotels through this website?',
    answer:
      'Currently, we do not offer booking services. We provide information and travel plans to help you on your journey.',
  },
];

export const metadata: Metadata = {
  title: 'FAQ',
  alternates: {
    canonical: new URL('/faq', 'https://tomokichidiary.netlify.app'),
  },
};

const FaqPage = () => {
  return (
    <div className="container mx-auto max-w-4xl py-12">
      <Card>
        <CardHeader>
          <CardTitle className="text-3xl font-bold tracking-tight">
            Frequently Asked Questions
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {FAQS.map((faq, index) => (
              <details key={index} className="group rounded-lg bg-gray-50 p-6">
                <summary className="flex cursor-pointer items-center justify-between font-medium text-gray-900">
                  {faq.question}
                  <span className="ml-4 flex-shrink-0">
                    <svg
                      className="h-6 w-6 transform transition-transform duration-200 group-open:-rotate-180"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M19 9l-7 7-7-7"
                      />
                    </svg>
                  </span>
                </summary>
                <p className="mt-4 text-gray-700">{faq.answer}</p>
              </details>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default FaqPage;
